const Constants = {
  REQUEST_DEVICE: 'REQUEST_DEVICE',
  RECEIVE_DEVICE: 'RECEIVE_DEVICE',
  CREATE_DEVICE: 'CREATE_DEVICE',

  ADD_DEVICE_LISTENER: 'ADD_DEVICE_LISTENER',
  NOTIFY: 'NOTIFY',

  VIDEO_STREAM_GET_LOCAL: 'VIDEO_STREAM_GET_LOCAL',

  START_MOTION_DETECTION: 'START_MOTION_DETECTION',
  CHANGE_DETECTOR: 'CHANGE_DETECTOR',

  UPDATE_TITLE: 'UPDATE_TITLE',
};

export default Constants;
