const Constants = {
  REQUEST_DEVICE: 'REQUEST_DEVICE',
  RECEIVE_DEVICE: 'RECEIVE_DEVICE',
  CREATE_DEVICE: 'CREATE_DEVICE',

  ADD_DEVICE_LISTENER: 'ADD_DEVICE_LISTENER',

  VIDEO_STREAM_GET_LOCAL: 'VIDEO_STREAM_GET_LOCAL',

  START_MOTION_DETECTION: 'START_MOTION_DETECTION',
  CHANGE_DETECTOR: 'CHANGE_DETECTOR',

  UPDATE_TITLE: 'UPDATE_TITLE',

  PUSH_NOTIFICATION_SET_SUPPORTED: 'PUSH_NOTIFICATION_SET_SUPPORTED',
  PUSH_NOTIFICATION_SET_DENIED: 'PUSH_NOTIFICATION_SET_DENIED',
  PUSH_NOTIFICATION_SET_SUBSCRIPTION: 'PUSH_NOTIFICATION_SET_SUBSCRIPTION',
  PUSH_NOTIFICATION_SUBSCRIBE: 'PUSH_NOTIFICATION_SUBSCRIBE',
  PUSH_NOTIFICATION_UNSUBSCRIBE: 'PUSH_NOTIFICATION_UNSUBSCRIBE',
  PUSH_NOTIFICATION_SUBSCRIBE_TO_DEVICE: 'PUSH_NOTIFICATION_SUBSCRIBE_TO_DEVICE',
  PUSH_NOTIFICATION_UNSUBSCRIBE_FROM_DEVICE: 'PUSH_NOTIFICATION_UNSUBSCRIBE_FROM_DEVICE',
  PUSH_NOTIFICATION_SEND: 'PUSH_NOTIFICATION_SEND',
};

export default Constants;
